### ISSUE TITLE
i'am run the quick install guider with README file.but no "pcsd " installed? 

### ISSUE THREAD

**Issue by blambin** [feist/pcs#8]

**Comment by feist** [comment]
The README should be updated with current instructions on how to get pcsd installed.

**Comment by lanxuan19831201** [comment]
how to  start the pcsd ???

**Comment by tomjelinek** [comment]
@lanxuan19831201 It depends on what initsystem your OS uses. If you have systemd, it's `systemctl start pcsd.service`. Otherwise it's probably `service pcsd start`. You may also want to configure your system to start pcsd automatically on boot, which you can do by running `systemctl enable pcsd.service`. Consult your OS documentation for details.
